name: ui_kit_interface
description: App resources.
version: 1.0.0
publish_to: none

environment:
  sdk: '>=2.18.0 <3.0.0'
  flutter: '>=3.3.0'

dependencies:
  flutter:
    sdk: flutter

  design_system:
    path: ../design_system

  webview_flutter: ^4.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  global_lints:
    path: ../global_lints
