name: social_login
description: social_login
version: 0.0.1
publish_to: none

environment:
  sdk: '>=2.18.0 <3.0.0'
  flutter: '>=3.3.0'

dependencies:
  flutter:
    sdk: flutter

  google_sign_in: ^6.1.6
  sign_in_with_apple: ^6.1.0
  jwt_decode: ^0.3.1

  core:
    git:
      url: git@github.com:tarek360/flutter_kit.git
      ref: 0.0.4
      path: flutter_kit/core

dev_dependencies:
  flutter_test:
    sdk: flutter
  global_lints:
    git:
      url: git@github.com:tarek360/flutter_kit.git
      ref: 0.0.4
      path: flutter_kit/global_lints
flutter:
